-- No 1
ALTER TABLE DETAILITEM 
ADD COLUMN "DISCOUNT%" INTEGER,
ADD COLUMN "NETPRICE" DECIMAL(15,2)



UPDATE DETAILITEM 
SET TAX = CASE 
           WHEN TOTALPRICE >= 1000000.00 THEN 0.11 * TOTALPRICE 
           ELSE 0.00 
         END,
    NETPRICE = TOTALPRICE + TAX;

-- No 2

SELECT R.COSTUMERNAME,R.RECEIPTNO,A.ALBUMNAME
FROM RECEIPT R
INNER JOIN  DETAILITEM D ON R.RECEIPTNO = D.RECEIPTNO 
INNER JOIN ALBUM A ON A.ALBUMNO = D.ALBUMNO 
INNER JOIN SINGER S ON S.SINGERID = A.SINGERID
WHERE a.RELEASEYEAR BETWEEN 2020 AND 2022;


-- No 3
SELECT R.COSTUMERNAME, R.RECEIPTDATE, ROUND(AVG(D.NETPRICE),2) AS NETAVERAGE
FROM RECEIPT R
JOIN DETAILITEM D ON R.RECEIPTNO = D.RECEIPTNO
WHERE R.RECEIPTDATE < '2022-12-05'
GROUP BY R.COSTUMERNAME, R.RECEIPTDATE;


-- nO 4

SELECT A.ALBUMNAME, S.SINGERNAME
FROM ALBUM A
INNER JOIN SINGER S ON  A.SINGERID = S.SINGERID 
INNER JOIN DETAILITEM D ON A.ALBUMNO = D.ALBUMNO
GROUP BY A.ALBUMNO, A.ALBUMNAME, S.SINGERNAME
HAVING SUM(D.AMOUNT) > 4;

-- No 5

SELECT A.ALBUMNO, A.ALBUMNAME, S.SINGERNAME, ROUND(SUM(D.NETPRICE),2) AS TOTALNETPRICE
FROM ALBUM A
JOIN SINGER S ON S.SINGERID = A.SINGERID
NATURAL LEFT JOIN DETAILITEM D
GROUP BY A.ALBUMNO, A.ALBUMNAME, S.SINGERNAME
HAVING SUM(D.NETPRICE) <
	(SELECT AVG(NETPRICE)
	 FROM DETAILITEM);

-- No 6
SELECT S.SINGERNAME, 
       SUM(D.amount) AS TOTAL_AMOUNT, 
       ROUND(SUM(D.NETPRICE), 2) AS TOTAL_NETPRICE
FROM SINGER S
INNER JOIN ALBUM A ON S.SINGERID = A.SINGERID 
INNER JOIN DETAILITEM D ON D.ALBUMNO = A.ALBUMNO 
GROUP BY S.SINGERNAME 
ORDER BY TOTAL_NETPRICE DESC



-- NO 7
SELECT ROUND(SUM(CASE WHEN ALBUMNAME = 'BE TOGETHER' THEN NETPRICE ELSE 0 END) * 100 / SUM(NETPRICE), 2) AS PERCENTAGE_NETPRICE
FROM SINGER S
INNER JOIN ALBUM A ON S.SINGERID = A.SINGERID 
INNER JOIN DETAILITEM D ON D.ALBUMNO = A.ALBUMNO
